CREATE TABLE support_tasks(
  
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  title VARCHAR(150) NOT NULL,

  staus VARCHAR(20) NOT NULL DEFAULT 'PENDING'
    CHECK (status In ('PENDING', 'IN_PROGRESS', 'RESOLVED'))

  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);